Bins Role uses offline keys
secure-systems-lab/peps pull request #1
Opened 2019-10-04 14:56 UTC by mnm678

Update the image and description so that the bins role uses offline keys

2019-10-07 13:54 UTC, lukpueh requested changes
The patch itself looks good to me, but there are other places in the document that need to be adopted. Here is one [paragraph that's now obsolete](https://github.com/secure-systems-lab/peps/blame/327f5cc8025ef6d1329617654c4b74c4073d5166/pep-0458.txt#L484-L486):

> Each of the "bin" roles SHOULD share the same key as the *bins* role, due to space efficiency,
and because there is no security advantage to requiring separate keys.

I suggest to grep for all occurrences of *"bin"* in the text to check for consistency.

2019-10-08 15:33 UTC, mnm678 commented
@lukpueh I fixed a couple more references to the online bins key. I decided to not change the references that are fixed in #4 to prevent a conflict.

2019-10-09 20:17 UTC, JustinCappos commented
@lukpueh, when you get a chance, can you re-review and merge if ready?

2019-10-09 20:59 UTC, trishankatdatadog requested changes

2019-10-09 20:59 UTC, trishankatdatadog commented on pep-0458.txt
> +delegated to by *bins*.  The *timestamp* and *snapshot*
```suggestion
delegated to by *bins* (i.e., *bin-n*).  The *timestamp* and *snapshot*
```

2019-10-09 20:59 UTC, trishankatdatadog commented on pep-0458.txt
>  and *snapshot* metadata will most likely be updated frequently (possibly every
```suggestion
*snapshot*, and *bin-n* metadata will most likely be updated frequently (possibly every
```

2019-10-09 20:59 UTC, trishankatdatadog commented on pep-0458.txt
> +will only be updated when new bins are added.  Therefore, *timestamp*
```suggestion
will only be updated when new bins are added.  Therefore, *timestamp*,
```

2019-10-09 20:59 UTC, trishankatdatadog commented on pep-0458.txt
> +This PEP proposes that the *bins* role's delegated roles sign for all
```suggestion
This PEP proposes that the *bin-n* roles roles sign for all
```

2019-10-09 20:59 UTC, trishankatdatadog commented on pep-0458.txt
>  The *root* and *targets* role metadata SHOULD expire in one year, because these
```suggestion
The metadata for the *root*, *targets*, and *bins* roles SHOULD each expire in one year, because these
```

2019-10-09 20:59 UTC, trishankatdatadog commented on pep-0458.txt
> +The *timestamp*, *snapshot*, and *bin-n* metadata SHOULD expire in one day
```suggestion
The *timestamp*, *snapshot*, and *bin-n* metadata SHOULD each expire in one day
```

2019-10-10 07:56 UTC, lukpueh commented
Merged into master manually with 4d1e05ccbb8c149a917ae9ca641cbeca31f9a48f after resolving a conflict (4969aed155a6a46f336c8a2fe9430eb0ea43ffbb --> b46c4c43150fa7a8dce427c9d2703210cea09cff).

2019-10-10 07:56 UTC, closed without merging