PEP 0458: clarify snapshot metadata compression
secure-systems-lab/peps pull request #30
Opened 2019-10-16 12:04 UTC by joshuagl

The snapshot metadata compression should be handled at a separate
layer, as TUF doesn't provide compression (see TAP 10).

An attempt to address #20

2019-10-16 15:06 UTC, lukpueh approved these changes
LGTM.

2019-10-16 21:26 UTC, trishankatdatadog requested changes
LGTM, pls add suggestion and fix conflict, tq

2019-10-16 21:26 UTC, trishankatdatadog commented on pep-0458.txt
> +this PEP.  However, due to the large number of delegated metadata, compressed
```suggestion
this PEP.  However, due to the large number of delegations, compressed
```

2019-10-17 08:41 UTC, joshuagl commented
I've force pushed the branch with the suggestion added and conflicts fixed.

2019-10-17 11:09 UTC, trishankatdatadog approved these changes
LGTM, pls add suggestion and fix conflict, tq

2019-10-17 11:09 UTC, trishankatdatadog commented on pep-0458.txt
> +versions of *snapshot* metadata SHOULD also be made available to clients via the
```suggestion
versions of all metadata SHOULD also be made available to clients via the
```

2019-10-17 11:37 UTC, joshuagl commented on pep-0458.txt
> +versions of *snapshot* metadata SHOULD also be made available to clients via the
addressed in force push

2019-10-17 11:38 UTC, merged