clarify bins and bin-n in the table
secure-systems-lab/peps pull request #34
Opened 2019-10-16 16:51 UTC by mnm678

Fixes #26 
Clarifies what happens if bins or bin-n keys are compromised. Please double check for correctness.

2019-10-16 23:29 UTC, trishankatdatadog requested changes
I think the analysis for the case where timestamp, snapshot, and bin-n has been compromised is inaccurate

Freeze and metadata inconsistency attacks are limited by earliest root, targets, and bins (but NOT bin-n) metadata expiration time

2019-10-17 14:05 UTC, lukpueh requested changes

2019-10-17 14:05 UTC, lukpueh commented on pep-0458.txt
>  +-----------------+-------------------+----------------+--------------------------------+
This should be "targets OR bins OR bin-n" or "targets OR any delegated targets".

Alternatively, if we expect the reader to understand the delegation hierarchy, i.e. that compromising *targets* allows to compromise *bins* allows to compromise *bin-n*, then it might be enough to only mention *bin-n*, which is what the attacker is after. It seems to me that that's the assumption in the row below.

If we go with one of my suggestions from the top, I'd also change the row below to mention targets, bins and bin-n, and not just bin-n, for consistency.

2019-10-17 14:05 UTC, lukpueh commented on pep-0458.txt
>  +-----------------+-------------------+----------------+--------------------------------+
What's the difference between "NO" and "NOT APPLICABLE" in this context?

2019-10-17 14:17 UTC, lukpueh commented on pep-0458.txt
>  +-----------------+-------------------+----------------+--------------------------------+
> If we go with one of my suggestions from the top, I'd also change the row below to mention targets, bins and bin-n, and not just bin-n, for consistency.

I take that back. Only mentioning "bin-n" makes a difference in regards to *Freeze Attack* and *Metadata Inconsistency Attack*. As @trishankatdatadog says above *targets* and *bins* expiration times can stop them. And shouldn't they also stop *Malicious updates*?

2019-10-17 14:20 UTC, lukpueh commented
> Freeze and metadata inconsistency attacks are limited by earliest root, targets, and bins (but NOT bin-n) metadata expiration time

I agree with @trishankatdatadog, if *bin-n* is compromised the attacker has control over their expiration time. Well spotted!

2019-10-17 14:34 UTC, mnm678 commented on pep-0458.txt
>  +-----------------+-------------------+----------------+--------------------------------+
I'll update to targets or bins or bin-n. 

The NO vs NOT APPLICABLE was in the original text. I think they mean the same thing so will change them all to NO for consistency.

2019-10-17 17:35 UTC, JustinCappos commented on pep-0458.txt
> +|                 | time              | time           |                                |
Should we also have a place for bins / targets compromise?  Isn't this missing?

2019-10-17 21:06 UTC, mnm678 commented
Thank you for all of the feedback. I incorporated some of it in the new table for #43. However, much of the work here assumes different keys for snapshot, timestamp, and bin-n, so I am closing this in favor of #43.

2019-10-17 21:06 UTC, closed without merging