Only use sha 512
secure-systems-lab/peps pull request #71
Opened 2019-11-20 18:24 UTC by mnm678

I removed mentions of sha256 per #67 and redid the metadata overhead calculations.

Please double check my math on the metadata calculations.

2019-11-20 19:01 UTC, joshuagl requested changes
Minor nit, otherwise looks good.

2019-11-20 19:01 UTC, joshuagl commented on pep-0458.txt
> +twice with their SHA-512 hash included in their
```suggestion
once with their SHA-512 hash included in their
```

2019-11-21 11:25 UTC, lukpueh requested changes
I cross-checked the numbers with the  [updated spreadsheet](https://docs.google.com/a/nyu.edu/spreadsheets/d/11_XkeHrf4GdhMYVqpYWsug6JNz5ZK6HvvmDZX0__K2I/edit?disco=AAAAD9TmS4), and they add up. There's a typo in one formula (see inline suggestions). Other than that LGTM! :)

2019-11-21 11:25 UTC, lukpueh commented on pep-0458.txt
> +| V7   | Avg size of bin-n metadata (bytes)                                                 | V4+V5+V76                    | 54,349    |
```suggestion
| V7   | Avg size of bin-n metadata (bytes)                                                 | V4+V5+V6                    | 54,349    |
```

2019-11-21 17:31 UTC, lukpueh approved these changes

2019-11-22 10:03 UTC, merged