Disambiguate bins
secure-systems-lab/peps pull request #8
Opened 2019-10-10 13:09 UTC by lukpueh

## This PR does
- above all try to disambiguate *targets* and delegated targets roles, i.e. *bins* and *bin-n* roles,
- it further fleshes out the *roles* entry in the *definitions* sections and removes the obsolete clarification why *snapshot* is not called *release*,
- it also fixes spelling.

## This PR does NOT (but should) solve the following issues:

- Why doesn't targets delegate directly to *bin-n* roles? What is the benefit of having an intermediate *bins* role? The only purpose I can see is semantic. Delegating from *targets* directly to *bin-n* would reduce complexity of this pep.

- The recommended number of bins was adjusted to 16,384, we should adopt that number in Figure 2 that shows `bin 1` to `bin 1024`, alternatively (and preferably) we can replace `1024` with `N`. 

- In section "Revoking Trust in Projects and Versions":
  - What is the difference between revoking trust in projects and revoking it in versions? If I understand correctly in both cases, the target files corresponding to that project or version need to be removed from the *bin-n* metadata they are listed in, which need to be re-signed with the online key. If that's accurate, why differentiate?
  - Also, is there a case where the *bins* role (offline key) needs to be resigned?

- In section "Key Compromise Analysis":
  - Disambiguate *bins* and *bin-n* in table.
  - Clarify what "projects targets metadata" is (paragraph under the table).
  - Maybe re-think the table. There are multiple instances that describe how,
 snapshot, timestamp and/or bin-n roles need to cooperate for an attacker to be successful, which seems less meaningful when these roles share the same online key, which is recommend in this pep.

Please review and and above all **comment** to the concerns and questions I am raising here!

 (cc @JustinCappos, @trishankatdatadog, @mnm678, @SantiagoTorres, @awwad. I'm also inviting @joshuagl who kindly volunteered to help.)

2019-10-10 15:34 UTC, JustinCappos commented
> Why doesn't targets delegate directly to bin-n roles? What is the benefit of having an intermediate bins role? The only purpose I can see is semantic. Delegating from targets directly to bin-n would reduce complexity of this pep.

It also makes it easier to revoke a single key or change the top level targets (to transition to PEP 480).  You don't need to re-download the bins -> bin-n mapping in this case, which is fairly large.

> What is the difference between revoking trust in projects and revoking it in versions? If I understand correctly in both cases, the target files corresponding to that project or version need to be removed from the bin-n metadata they are listed in, which need to be re-signed with the online key. If that's accurate, why differentiate?

It's the same in PEP 458.  They are different in PEP 480, which was what I was thinking of with my original PR, so this should be fixed.

> Also, is there a case where the bins role (offline key) needs to be resigned?

Not unless there was a weakness in how the keys were generated.

2019-10-10 16:53 UTC, trishankatdatadog requested changes
VERY good observations, Lukas, thanks! I just have some minor changes, please.

I'll try to work separately on your other comments...

2019-10-10 16:53 UTC, trishankatdatadog commented on pep-0458.txt
> +  delegated directly by the *root* role, i.e. *timestamp*, *snapshot* and
```suggestion
  specified directly by the *root* role, i.e. *timestamp*, *snapshot* and
```

2019-10-10 16:53 UTC, trishankatdatadog commented on pep-0458.txt
> +  delegated directly by the *root* role, i.e. *timestamp*, *snapshot* and
Let's not overload the term "delegate"

2019-10-10 16:53 UTC, trishankatdatadog commented on pep-0458.txt
> +will only be updated when a new *bin-n* role is added.  Therefore, *timestamp*,
```suggestion
will only be updated when a *bin-n* role is added, updated, or removed.  Therefore, *timestamp*,
```

2019-10-10 16:53 UTC, trishankatdatadog commented on pep-0458.txt
> +in advance, when a client performs an update. Instead the *timestamp* metadata
```suggestion
in advance, when a client performs an update. The *timestamp* metadata
```

2019-10-10 16:53 UTC, trishankatdatadog commented on pep-0458.txt
> +serves as version root. That is, it lists the
```suggestion
lists the
```

2019-10-10 16:53 UTC, trishankatdatadog commented on pep-0458.txt
>  version of the *snapshot* metadata, which in turn lists the versions of *root*,
```suggestion
version of the *snapshot* metadata, which in turn lists the versions of the
```

2019-10-10 16:53 UTC, trishankatdatadog commented on pep-0458.txt
> +delegated *bin-n* metadata.
```suggestion
*bin-n* metadata.
```

2019-10-10 16:53 UTC, trishankatdatadog commented on pep-0458.txt
> +project transaction process MUST inform the snapshot process about new
```suggestion
project transaction process MUST inform the snapshot process about any new
```

2019-10-10 16:53 UTC, trishankatdatadog commented on pep-0458.txt
> +Finally, project transaction processes SHOULD keep in memory the latest *bin-n*
```suggestion
Finally, project transaction processes SHOULD use the latest *bin-n*
```

2019-10-10 16:53 UTC, trishankatdatadog commented on pep-0458.txt
>  process MUST keep in memory the latest working set of *root*, *targets*, and
```suggestion
process SHOULD use the latest working set of the *targets* and all
```

2019-10-10 16:53 UTC, trishankatdatadog commented on pep-0458.txt
> +delegated targets roles (i.e. *bins* and *bin-n* roles).  Upon an update, the
```suggestion
delegated targets roles' (i.e. *bins* and *bin-n* roles) metadata.  Upon an update, the
```

2019-10-10 20:25 UTC, trishankatdatadog commented on pep-0458.txt
> +Signing updated *snapshot*, *timestamp*, and *bin-n* metadata needs to be done on each
```suggestion
Signing updated *timestamp*, *snapshot*, and *bin-n* metadata needs to be done on each
```

2019-10-10 21:16 UTC, trishankatdatadog commented
@lukpueh pushed your other comments [here](https://github.com/secure-systems-lab/peps/issues/15)

2019-10-11 11:35 UTC, lukpueh commented
Thanks for the updates @trishankatdatadog! I batch committed them in c8b0657. Let's merge here and address the remaining comments in #15 (FYI, I also moved @JustinCappos comment over there).

2019-10-11 11:35 UTC, merged